### PR TITLE
Updated Readme. Added polarities on PCB  and component values on both sch&PCB

### PR DESCRIPTION
**Pull request by CJGuirao**
Updated the values of all the components in schematics and PCB. 
Modified silkscreen to print diode and LED polarity, and added component values.

created release v1.2 folder that contains:
Generated new Gerber files. 
The original firmware for the STM32 chips
The 64k version of the firmware that works on the CH32

### CODE REVIEW

**Comment by CJGuirao** [comment]
I dedicated a bit more time to the main readme. 
I'll continue working on it to write the assembly instructions on the next days

**Comment by shaise** [comment]
Hi Guirao,

Great work! thanks!
But before I merge it, can you please remove all the backup zip files? I think they are not necessary. 
Thanks!

shai

**Comment by CJGuirao** [comment]
Will do. Thanks

**Comment by CJGuirao** [comment]
I removed all the newly created backup files from the kicad backup folder.
I originally left them because I saw there was already backups there. So I thought you wanted to keep them.

Also I copied the DiseProgrammer.zip from v1.1 to v1.2 folder in release so new end users have everything they need in one folder.

**Comment by shaise** [comment]
Thanks!

**Pull request merged**
